"use client";
import React from "react";

const PrivacyPolicy: React.FC = () => {
  const handleRequestDeletion = () => {
    window.location.href =
      "mailto:support@gmail.com?subject=Data Deletion Request&body=Dear Leadlly Edusolutions Support Team,%0D%0A%0D%0AI would like to request the deletion of all my personal data held by Leadlly Edusolutions as per your Privacy Policy.%0D%0A%0D%0APlease confirm the deletion process and notify me once it has been completed.%0D%0A%0D%0AThank you.%0D%0A%0D%0ARegards,%0D%0A[Your Name]";
  };

  return (
    <div className="max-w-4xl mx-auto py-10 px-5">
      <h1 className="text-3xl font-bold text-[#8B4CF4] mb-6">Privacy Policy</h1>
      <p className="text-gray-700 mb-4">
        At Leadlly Edusolutions, we value your privacy and are committed to
        protecting your personal data. This privacy policy outlines the types of
        information we collect, how we use it, and the steps we take to
        safeguard your data.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">1. Introduction</h2>
      <p className="text-gray-700 mb-4">
        Welcome to Leadlly edusolutions private limited. Leadlly edusolutions
        private limited (“us”, “we”, or “our”) operates leadlly.in (hereinafter
        referred to as “Service”). Our Privacy Policy governs your visit to
        leadlly.in, and explains how we collect, safeguard and disclose
        information that results from your use of our Service. We use your data
        to provide and improve Service. By using Service, you agree to the
        collection and use of information in accordance with this policy. Unless
        otherwise defined in this Privacy Policy, the terms used in this Privacy
        Policy have the same meanings as in our Terms and Conditions. Our Terms
        and Conditions (“Terms”) govern all use of our Service and together with
        the Privacy Policy constitutes your agreement with us (“agreement”).
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">2. Definition</h2>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">SERVICE</b> means the leadlly.in website
        operated by Leadlly Edusolutions Private Limited.
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">PERSONAL DATA</b> means data about a living
        individual who can be identified from that data (or from those and other
        information either in our possession or likely to come into our
        possession).
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">USAGE DATA</b> is data collected automatically
        either generated by the use of Service or from Service infrastructure
        itself (for example, the duration of a page visit).
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">COOKIES</b> are small files stored on your
        device (computer or mobile device).
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">DATA CONTROLLER</b> means a natural or legal
        person who (either alone or jointly or in common with other persons)
        determines the purposes for which and the manner in which any personal
        data are, or are to be, processed. For the purpose of this Privacy
        Policy, we are a Data Controller of your data.
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">DATA PROCESSORS (OR SERVICE PROVIDERS)</b>{" "}
        means any natural or legal person who processes the data on behalf of
        the Data Controller. We may use the services of various Service
        Providers in order to process your data more effectively.
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">DATA SUBJECT</b> is any living individual who
        is the subject of Personal Data.
      </p>
      <p className="text-gray-700 mb-4">
        <b className="font-bold">THE USER</b> is the individual using our
        Service. The User corresponds to the Data Subject, who is the subject of
        Personal Data.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">
        4. Types of Data Collected
      </h2>
      <h3 className="text-xl font-semibold mb-4">Personal Data</h3>
      <p className="text-gray-700 mb-4">
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
      </p>
      <ul className="list-disc pl-5 mb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, Country, State, Province, ZIP/Postal code, City</li>
        <li>Cookies and Usage Data</li>
      </ul>
      <p className="text-gray-700 mb-4">
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link.
      </p>

      <h3 className="text-xl font-semibold mb-4">Usage Data</h3>
      <p className="text-gray-700 mb-4">
        We may also collect information that your browser sends whenever you
        visit our Service or when you access Service by or through any device
        (“Usage Data”).
      </p>
      <p className="text-gray-700 mb-4">
        This Usage Data may include information such as your computer’s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that you visit, the time and date of your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>

      <h3 className="text-xl font-semibold mb-4">Tracking Cookies Data</h3>
      <p className="text-gray-700 mb-4">
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information. Cookies are files with a
        small amount of data which may include an anonymous unique identifier.
        Cookies are sent to your browser from a website and stored on your
        device.
      </p>
      <p className="text-gray-700 mb-4">
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <p className="text-gray-700 mb-4">Examples of Cookies we use:</p>
      <ul className="list-disc pl-5 mb-4">
        <li>Session Cookies: We use Session Cookies to operate our Service.</li>
        <li>
          Preference Cookies: We use Preference Cookies to remember your
          preferences and various settings.
        </li>
        <li>
          Security Cookies: We use Security Cookies for security purposes.
        </li>
        <li>
          Advertising Cookies: Advertising Cookies are used to serve you with
          advertisements that may be relevant to you and your interests.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mb-4">Other Data</h3>
      <p className="text-gray-700 mb-4">
        While using our Service, we may also collect the following information:
        sex, age, date of birth, place of birth, passport details, citizenship,
        registration at place of residence and actual address, telephone number
        (work, mobile), details of documents on education, qualification,
        professional training, employment agreements, NDA agreements,
        information on bonuses and compensation, information on marital status,
        family members, social security (or other taxpayer identification)
        number, office location and other data.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">5. Use of Data</h2>
      <p className="text-gray-700 mb-4">
        Leadlly Edusolutions Private Limited uses the collected data for various
        purposes:
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>To provide and maintain our Service;</li>
        <li>To notify you about changes to our Service;</li>
        <li>
          To allow you to participate in interactive features of our Service
          when you choose to do so;
        </li>
        <li>To provide customer support;</li>
        <li>
          To gather analysis or valuable information so that we can improve our
          Service;
        </li>
        <li>To monitor the usage of our Service;</li>
        <li>To detect, prevent and address technical issues;</li>
        <li>To fulfill any other purpose for which you provide it;</li>
        <li>
          To carry out our obligations and enforce our rights arising from any
          contracts entered into between you and us, including for billing and
          collection;
        </li>
        <li>
          To provide you with notices about your account and/or subscription,
          including expiration and renewal notices, email-instructions, etc.;
        </li>
        <li>
          To provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information;
        </li>
        <li>For any other purpose with your consent.</li>
      </ul>

      {/* Section 6 - Retention of Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">6. Retention of Data</h2>
      <p className="text-gray-700 mb-4">
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies. We will also retain Usage Data for internal
        analysis purposes. Usage Data is generally retained for a shorter
        period, except when this data is used to strengthen the security or to
        improve the functionality of our Service, or we are legally obligated to
        retain this data for longer time periods.
      </p>

      {/* Section 7 - Transfer of Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">7. Transfer of Data</h2>
      <p className="text-gray-700 mb-4">
        Your information, including Personal Data, may be transferred to – and
        maintained on – computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction. If you are located
        outside India and choose to provide information to us, please note that
        we transfer the data, including Personal Data, to India and process it
        there. Your consent to this Privacy Policy followed by your submission
        of such information represents your agreement to that transfer. Leadlly
        Edusolutions Private Limited will take all the steps reasonably
        necessary to ensure that your data is treated securely and in accordance
        with this Privacy Policy and no transfer of your Personal Data will take
        place to an organization or a country unless there are adequate controls
        in place including the security of your data and other personal
        information.
      </p>

      {/* Section 8 - Disclosure of Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        8. Disclosure of Data
      </h2>
      <p className="text-gray-700 mb-4">
        We may disclose personal information that we collect, or you provide:
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </li>
        <li>
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
        </li>
        <li>To our subsidiaries and affiliates;</li>
        <li>
          To contractors, service providers, and other third parties we use to
          support our business;
        </li>
        <li>To fulfill the purpose for which you provide it;</li>
        <li>
          For any other purpose disclosed by us when you provide the
          information;
        </li>
        <li>With your consent in any other cases;</li>
        <li>
          If we believe disclosure is necessary or appropriate to protect the
          rights, property, or safety of the Company, our customers, or others.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold mt-6 mb-4">9. Security of Data</h2>
      <p className="text-gray-700 mb-4">
        The security of your data is important to us, but remember that no
        method of transmission over the Internet, or method of electronic
        storage is 100% secure. While we strive to use commercially acceptable
        means to protect your Personal Data, we cannot guarantee its absolute
        security.
      </p>

      {/* Section 10 - Your Data Protection Rights Under GDPR */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        10. Your Data Protection Rights Under GDPR
      </h2>
      <p className="text-gray-700 mb-4">
        If you are a resident of the European Economic Area (EEA), you have
        certain data protection rights. Leadlly Edusolutions aims to take
        reasonable steps to allow you to correct, amend, delete, or limit the
        use of your Personal Data.
      </p>

      <p className="text-gray-700 mb-4">
        If you wish to be informed about what Personal Data we hold about you
        and if you want it to be removed from our systems, please contact us.
      </p>

      {/* Section 11 - Service Providers */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        11. Service Providers
      </h2>
      <p className="text-gray-700 mb-4">
        We may employ third party companies and individuals to facilitate our
        Service (“Service Providers”), provide the Service on our behalf,
        perform Service-related services or assist us in analyzing how our
        Service is used.
      </p>

      <p className="text-gray-700 mb-4">
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>

      {/* Section 12 - Analytics */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">12. Analytics</h2>
      <p className="text-gray-700 mb-4">
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>
          <b>Google Analytics:</b> Google Analytics is a web analytics service
          offered by Google that tracks and reports website traffic. Google uses
          the data collected to track and monitor the use of our Service. This
          data is shared with other Google services. Google may use the
          collected data to contextualize and personalize the ads of its own
          advertising network.
        </li>
      </ul>

      {/* Section 13 - Links to Other Sites */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        13. Links to Other Sites
      </h2>
      <p className="text-gray-700 mb-4">
        Our Service may contain links to other sites that are not operated by
        us. If you click on a third-party link, you will be directed to that
        third party’s site. We strongly advise you to review the Privacy Policy
        of every site you visit.
      </p>

      <p className="text-gray-700 mb-4">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third-party sites or services.
      </p>

      {/* Section 14 - Children's Privacy */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        14. Children's Privacy
      </h2>
      <p className="text-gray-700 mb-4">
        Our Service does not address anyone under the age of 18 (“Children”).
      </p>

      <p className="text-gray-700 mb-4">
        We do not knowingly collect personally identifiable information from
        anyone under the age of 18. If you are a parent or guardian and you are
        aware that your Children has provided us with Personal Data, please
        contact us. If we become aware that we have collected Personal Data from
        children without verification of parental consent, we take steps to
        remove that information from our servers.
      </p>

      {/* Section 15 - Changes to This Privacy Policy */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        15. Changes to This Privacy Policy
      </h2>
      <p className="text-gray-700 mb-4">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>

      <p className="text-gray-700 mb-4">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      {/* Section 16 - Contact Us */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">16. Contact Us</h2>
      <p className="text-gray-700 mb-4">
        If you have any questions about this Privacy Policy, please contact us:
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>By email: privacy@leadlly.com</li>
        <li>By visiting this page on our website: www.leadlly.com/contact</li>
        <li>By phone number: +91 1234567890</li>
      </ul>

      {/* Section 17 - Additional Information */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        17. Additional Information
      </h2>
      <p className="text-gray-700 mb-4">
        <b>How We Protect Your Data:</b>
        <br />
        We use appropriate technical and organizational measures to protect the
        Personal Data that we collect and process about you. The measures we use
        are designed to provide a level of security appropriate to the risk of
        processing your Personal Data.
      </p>

      <p className="text-gray-700 mb-4">
        <b>Data Breach:</b>
        <br />
        In the event that we become aware of a security breach involving your
        Personal Data, we will provide you with appropriate notice in accordance
        with applicable legal requirements.
      </p>

      {/* Section 18 - Data Controller */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">18. Data Controller</h2>
      <p className="text-gray-700 mb-4">
        Leadlly Edusolutions Private Limited is the data controller for the
        purposes of this Privacy Policy. This means that we are responsible for
        deciding how we hold and use Personal Data about you.
      </p>

      {/* Section 19 - Legal Basis for Processing Personal Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">
        19. Legal Basis for Processing Personal Data
      </h2>
      <p className="text-gray-700 mb-4">
        We may process Personal Data relating to you if one of the following
        applies:
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>
          You have given your consent for the processing of your Personal Data
          for one or more specific purposes;
        </li>
        <li>
          Processing is necessary for the performance of a contract to which you
          are a party or in order to take steps at your request prior to
          entering into a contract;
        </li>
        <li>
          Processing is necessary for compliance with a legal obligation to
          which we are subject;
        </li>
        <li>
          Processing is necessary to protect the vital interests of you or of
          another natural person;
        </li>
        <li>
          Processing is necessary for the performance of a task carried out in
          the public interest or in the exercise of official authority vested in
          the controller;
        </li>
        <li>
          Processing is necessary for the purposes of the legitimate interests
          pursued by us or by a third party.
        </li>
      </ul>

      {/* Section 20 - Complaints */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">20. Complaints</h2>
      <p className="text-gray-700 mb-4">
        If you have any concerns about our handling of your Personal Data, you
        have the right to make a complaint at any time to the appropriate
        supervisory authority in your country.
      </p>

      {/* Section 21 - Definitions */}
      <h2 className="text-2xl font-semibold mt-6 mb-4">21. Definitions</h2>
      <p className="text-gray-700 mb-4">
        <b>Personal Data:</b>
        <br />
        Personal Data means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>

      <p className="text-gray-700 mb-4">
        <b>Usage Data:</b>
        <br />
        Usage Data is data collected automatically either generated by the use
        of the Service or from the Service infrastructure itself (for example,
        the duration of a page visit).
      </p>

      <h2 id="delete" className="text-2xl font-semibold mt-6 mb-4">
        22. Request Deletion of Personal Data
      </h2>
      <p className="text-gray-700 mb-4">
        You have the right to request the deletion of your personal data held by
        Leadlly Edusolutions. To initiate the deletion process, please send an
        email to{" "}
        <a
          href="mailto:support@leadlly.in"
          className="text-primary-blue underline"
        >
          support@gmail.com
        </a>{" "}
        with the subject line "<b>Data Deletion Request</b>".
      </p>

      <p className="text-gray-700 mb-4">
        In your email, please provide the following details:
      </p>

      <ul className="list-disc pl-6 text-gray-700 mb-4">
        <li>Your full name</li>
        <li>The email address associated with your account</li>
        <li>A statement requesting the deletion of your personal data</li>
      </ul>

      <button
        onClick={handleRequestDeletion}
        className="bg-[#8B4CF4] text-white py-2 px-4 rounded-md hover:bg-primary-blue-dark transition duration-300"
      >
        Request Data Deletion
      </button>
    </div>
  );
};

export default PrivacyPolicy;
